### ISSUE TITLE
moment() objects not working

### ISSUE THREAD

**Issue by ralyodio** [tlhunter/node-easyxml#2]
```
Error: _isAMomentObjectcontained non_string_attribute
   at EasyXml.parseChildElement (/Users/username/projects/getrandomdate/node_modules/easyxml/index.js:186:27)
   at EasyXml.parseChildElement (/Users/username/projects/getrandomdate/node_modules/easyxml/index.js:236:22)
   at EasyXml.render (/Users/username/projects/getrandomdate/node_modules/easyxml/index.js:109:10)
   at /Users/username/projects/getrandomdate/server/index.js:72:25
   at Layer.handle [as handle_request] (/Users/username/projects/getrandomdate/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/username/projects/getrandomdate/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/Users/username/projects/getrandomdate/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/Users/username/projects/getrandomdate/node_modules/express/lib/router/layer.js:82:5)
   at proto.handle.c (/Users/username/projects/getrandomdate/node_modules/express/lib/router/index.js:235:24)
   at param (/Users/username/projects/getrandomdate/node_modules/express/lib/router/index.js:332:14)
```

unrelated error, but no way to notify author since he's disabled issues. When using moment() objects, the easyXml serializer craps out.

**Comment by tlhunter** [comment]
This issue is (finally) fixed in a separate PR. It can break existing apps so I'll make it a MAJOR 2.0 release. I'm going to get a few more MINOR changes out before releasing.
